build_networkmanager_dmenu:
	@echo "NM-Dmenu built"

link_networkmanager_dmenu:
	ln $(LN_FLAGS) $(DOTFILES)/misc/networkmanager_dmenu $(HOME)/.config/networkmanager-dmenu/config.ini

build_misc: build_networkmanager_dmenu

link_misc: link_networkmanager_dmenu
