### Opacity
menu-opacity = 0.90;
inactive-opacity = 0.85;
active-opacity = 0.90;
opacity-rule = [ 
  "99:_NET_WM_STATE@[0]:32a = '_NET_WM_STATE_FULLSCREEN'",
  "99:_NET_WM_STATE@[1]:32a = '_NET_WM_STATE_FULLSCREEN'",
  "99:_NET_WM_STATE@[2]:32a = '_NET_WM_STATE_FULLSCREEN'",
  "99:_NET_WM_STATE@[3]:32a = '_NET_WM_STATE_FULLSCREEN'",
  "99:_NET_WM_STATE@[4]:32a = '_NET_WM_STATE_FULLSCREEN'",
  "75:name = 'i3lock'",
  "99:class_g = 'Terraria.bin.x86_64'",
  "99:class_g = 'gl'"
]
### Blur options
blur-background = true;
blur-strength = 8;
