bg_default: &bg_default {stack: [{background: {color: %{{background.code}}FF}}, {underline: {size: 4, color: %{{color3.code}}FF}}]}
std_underline: &std_underline {underline: { size: 2, color: %{{color3.code}}FF}}
bar:
  height: 40
  location: top
  font: mono:pixelsize=30px
  spacing: 5
  margin: 0
  layer: bottom
  foreground: %{{foreground.code}}FF
  background: %{{background.code}}FF
  monitor: *monitor
  left:
  - river:
      anchors:
        - base: &river_base
            left-margin: 10
            right-margin: 13 
            default: {string: {text: "{tag}"}}
            tag: id
            values:
              0: {string: {text: 🄌}}
              1: {string: {text: ➊}}  
              2: {string: {text: ➋}}  
              3: {string: {text: ➌}}  
              4: {string: {text: ➍}}  
              5: {string: {text: ➎}}  
              6: {string: {text: ➏}}  
              7: {string: {text: ➐}}  
              8: {string: {text: ➑}}  
              9: {string: {text: ➒}}  
              10: {string: {text: ➓}}  

      content:
        map:
          deco:
            background:
              color: %{{color8.code}}FF
          on-click: 
            left: sh -c "riverctl set-focused-tags $((1 << ({id} - 1)))"
            right: sh -c "riverctl toggle-focused-tags $((1 << ({id} -1)))"
            middle: sh -c "riverctl toggle-view-tags $((1 << ({id} -1)))"
          tag: state
          values:
            urgent:
              map:
                <<: *river_base
                deco: {background: {color: %{{background.code}}FF}}
            focused:
              map:
                <<: *river_base
                deco: *bg_default
            visible:
              map:
                tag: occupied
                values:
                  false: {map: {<<: *river_base}}
                  true: {map: {<<: *river_base, deco: *bg_default}}
            unfocused:
              map:
                <<: *river_base
            invisible:
              map:
                tag: occupied
                values:
                  false: {empty: {}}
                  true: {map: {<<: *river_base, deco: {underline: {size: 3, color: %{{color3.code}}FF}}}}
  right:
  - network:
      name: eth0
      content:
      - map:
          deco: *bg_default
          tag: state
          values:
            up:
              string:
                text: ""
  - network:
      name: wlan0
      content:
      - map:
          deco: *bg_default
          tag: state
          default: {string: {text: }}
          values:
            down: {string: {text: }}
            up:
              map:
                tag: ipv4
                default:
                  - string: {text: }
                  - string: {text: "{ssid}"}
                values:
                  "":
                    - string: {text: }
                    - string: {text: "{ssid}", foreground: %{{foreground.code}}FF}
  - backlight:
      name: intel_backlight
      content:
      - string:
          deco: *bg_default
          text: 
      - string:
          deco: *bg_default
          text: "{percent}%"
  - battery:
      name: BAT0
      poll-interval: 30
      anchors:
        discharging: &discharging
          list:
            items:
              - ramp:
                  tag: capacity
                  items:
                    - string: {text: , foreground: %{{color4.code}}FF}
                    - string: {text: , foreground: %{{color4.code}}FF}
                    - string: {text: }
                    - string: {text: }
                    - string: {text: }
                    - string: {text: }
                    - string: {text: }
                    - string: {text: }
                    - string: {text: }
                    - string: {text: , foreground: %{{color2.code}}FF}
              - string: {text: "{capacity}% ({estimate})"}
      content:
        map:
          deco: *bg_default
          tag: state
          values:
            unknown:
              <<: *discharging
            discharging:
              <<: *discharging
            charging:
              - string: {text: , foreground: %{{color2.code}}FF}
              - string: {text: "{capacity}% ({estimate})"}
            full:
              - string: {text: , foreground: %{{color2.code}}FF}
              - string: {text: "{capacity}%"}
            not charging:
              - ramp:
                  tag: capacity
                  items:
                    - string: {text:  , foreground: %{{color4.code}}FF}
                    - string: {text:  , foreground: %{{color12.code}}FF}
                    - string: {text:  , foreground: %{{color10.code}}FF}
                    - string: {text:  , foreground: %{{color10.code}}FF}
                    - string: {text:  , foreground: %{{color10.code}}FF}
                    - string: {text:  , foreground: %{{color10.code}}FF}
                    - string: {text:  , foreground: %{{color2.code}}FF}
                    - string: {text:  , foreground: %{{color2.code}}FF}
                    - string: {text:  , foreground: %{{color2.code}}FF}
                    - string: {text:  , foreground: %{{color2.code}}FF}
              - string: {text: "{capacity}%"}
  - clock:
      time-format: "%H:%M %Z"
      content:
        - string:
            text: 
            deco: *bg_default
        - string:
            text: "{time}"
            deco: *bg_default
