global:
  installCommand: paru -S --needed --noconfirm %s
  dotfiles: ~/dotfiles
  gitUrl: git@github.com:LoricAndre/dotfiles
variables:
  color:
    bg: 282a36
    fg: d0d0d0
    0: 4e4e4e
    1: d68787 
    2: 5f865f
    3: d8af5f
    4: 85add4
    5: d7afaf
    6: 87afaf
    7: d0d0d0
    8: 44475a
    9: d75f87
    10: 87af87
    11: ffd787 
    12: add4fb
    13: ffafaf
    14: 87d7d7
    15: e4e4e4
  font: Iosevka Nerd Font Mono
  font_size: 11
  app:
    term: kitty
    browser: firefox
modules:
  yrice: {}
  neovim:
    dirname: nvim
    packageName: neovim-git
    dependencies: 
    - fzf
    - ripgrep
    - bat
    - lazygit
    - ranger
    - xclip
    - python-neovim
    files:
    - init.lua
    - plugin
    - lua/plugins
    - lua/utils.lua
    - source: lua/colors.lua
      parse: true
  waybar:
    enabled: false
    packageName: waybar
    files:
    - source: style.css
      parse: true
    - config
  yambar:
    enabled: false
    packageName: yambar
    files:
      - source: config.yaml
        parse: true
  bin:
    targetDir: ~/bin
  bspwm:
    enabled: false
    packageName: bspwm
    files:
    - source: bspwmrc
      target: bspwm
      parse: true
  fontconfig:
    targetDir: ~/.config/fontconfig/conf.d/
    files:
    - source: monospace
      target: 99-monospace.conf
      parse: true
  kitty:
    packageName: kitty
    files:
    - source: conf
      target: kitty.conf
      parse: true
    - source: colors
      target: kitty.colors
      parse: true
  lazygit:
    packageName: lazygit
  misc:
    targetDir: '~'
    files:
    - source: xinitrc
      target: .xinitrc
  neofetch:
    packageName: neofetch
  picom:
    enabled: false
    packageName: picom-tryone-git
  polybar:
    enabled: false
    packageName: polybar
    files:
    - source: polybar.conf
      parse: true
  ranger:
    packageName: ranger
  river:
    packageName: river
    dependencies:
    - rivercarro-git
    - disman
    - wofi
    - xwayland
    postSteps:
    - chmod +x ~/.config/river/init
    requires:
    - yambar
    files:
      - source: init
        parse: true
  sxhkd:
    enabled: false
    packageName: sxhkd
  xresources:
    targetDir: '~'
    files:
    - source: xresources
      target: .Xresources
      parse: true
  zsh:
    packageName: zsh
    targetDir: '~'
    preSteps: 
    - mkdir -p ~/.cache/zsh
    files:
    - source: zshrc
      target: .zshrc
    - source: aliases
      target: .zshaliases
    - source: profile
      target: .zprofile
    - source: antigen.zsh
      target: .antigen.zsh
    - source: completions
      target: .zshcompletions
  wezterm:
    enabled: false
    packageName: wezterm
    files:
    - source: wezterm.lua
      parse: true
  tmux:
    enabled: false
    targetDir: ~
    files:
    - source: tmux.conf
      target: .tmux.conf
  mako:
    packageName: mako
    files:
    - source: config
      parse: true
