#!/usr/bin/env bash
for file in $(git diff --cached --name-only --diff-filter=ACM); do
  if [[ $file == .* ]] || [[ ! $file == */* ]]; then
    echo "Skipping $file"
  else
    echo "Applying $file"
    dir=$(realpath $file --relative-to $(pwd) | cut -d'/' -f1)
    if [[ ! $dirs == *"$dir"* ]]; then
      dirs="$dirs $dir"
    fi
  fi
done
./bin/dots apply $dirs