# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[](bold green)'
error_symbol = '[](bold red)'

[username]
show_always = true

[time]
disabled = false

[aws]
disabled = true

# custom module for jj status
[custom.jj]
ignore_timeout = true
description = "The current jj status"
detect_folders = [".jj"]
symbol = "🥋 "
command = '''
jj log --revisions @ --no-graph --ignore-working-copy --color always --limit 1 --template '
  separate(" ",
    change_id.shortest(4),
    bookmarks,
    "|",
    concat(
      if(conflict, "💥"),
      if(divergent, "🚧"),
      if(hidden, "👻"),
      if(immutable, "🔒"),
    ),
    raw_escape_sequence("\x1b[1;32m") ++ if(empty, "(empty)"),
    raw_escape_sequence("\x1b[1;32m") ++ coalesce(
      truncate_end(29, description.first_line(), "…"),
      "(no description set)",
    ) ++ raw_escape_sequence("\x1b[0m"),
  )
'
'''

# optionally disable git modules
[git_state]
disabled = true
[custom.git_state]
when = "! jj root --ignore-working-copy"
command = "starship module git_state"
description = "Only show git_state if we're not in a jj repo"

[git_commit]
disabled = true

[custom.git_commit]
when = "! jj root --ignore-working-copy"
command = "starship module git_commit"
description = "Only show git_commit if we're not in a jj repo"

[git_branch]
disabled = true
ignore_submodules = true

[custom.git_branch]
when = "! jj root --ignore-working-copy"
command = "starship module git_branch"
description = "Only show git_branch if we're not in a jj repo"

[git_metrics]
disabled = true
ignore_submodules = true

[custom.git_metrics]
when = "! jj root --ignore-working-copy"
command = "starship module git_metrics"
description = "Only show git_metrics if inside a git repo"

[git_status]
disabled = true
ignore_submodules = true

[custom.git_status]
when = "! jj root --ignore-working-copy"
command = "starship module git_status"
description = "Only show git_status if inside a git repo"
