module_separator = " "

[bookmarks]
search_depth = 10
exclude = []

[[module]]
type = "Bookmarks"
separator = " "
color = "Magenta"
behind_symbol = "⇡"

[[module]]
type = "Commit"
max_length = 16

[[module]]
type = "State"
separator = " "

[module.conflict]
disabled = false
text = "𐔧"
color = "Red"

[module.divergent]
disabled = false
text = "󰓁"
color = "Cyan"

[module.empty]
disabled = false
text = "󰟢"
color = "Yellow"

[module.immutable]
disabled = false
text = ""
color = "Yellow"

[module.hidden]
disabled = false
text = ""
color = "Yellow"

[[module]]
type = "Metrics"
template = "[{changed}{added}{removed}]"
color = "Magenta"

[module.changed_files]
prefix = ""
suffix = ""
color = "Cyan"

[module.added_lines]
prefix = "+"
suffix = ""
color = "Green"

[module.removed_lines]
prefix = "-"
suffix = ""
color = "Red"
