#! /bin/sh
#Various settings
bspc config gapless_monocle true
bspc config borderless_monocle true
bspc config single_monocle true
bspc config paddingless_monocle false
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
## Honor size hints: do not make windows smaller than they wish to be
bspc config honor_size_hints true 

# Set the border colors.
bspc config normal_border_color "#{{color1}}"
bspc config active_border_color "#{{color2}}"
bspc config focused_border_color "#{{color15}}"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "#{{color1}}"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "#{{color1}}"
bspc config border_width 1

bspc config focus_follows_pointer true

#Settings for manual splitting
bspc config split_ratio         0.55

setxkbmap fr -option caps:escape,shift:both_capslock
xsetroot -cursor_name left_ptr
xrandr --auto && autorandr --change

bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 10
bspc monitor DP1 -d 1 2 3 4 5 6 7 8 9 10
bspc config top_padding 25
bspc rule -a scratchterm sticky=on state=floating hidden=on rectangle=1918x600+0+25

bspc rule -a KeePass2 desktop=^10
bspc rule -a Slack desktop=^1

[ -z $(pgrep sxhkd) ] && sxhkd &
pkill polybar
for m in $(bspc query -M --names); do
    MONITOR=$m polybar top &
done
[ -z $(bspc query -T -d | grep "scratchterm") ] && xst -c scratchterm &
pkill bspwm_wins.sh; bspwm_wins.sh & 
udiskie &
dunst &
picom &
feh --bg-fill ~/wallpaper.png
xautolock -time 10 -locker "betterlockscreen -l" -detectsleep
pgrep slack || slack &
# pulseaudio --start
