#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x conky > /dev/null || (conky && \
  conky -c ~/.config/conky/gcal.conf && \
  conky -c ~/.config/conky/bspwm.conf && \
  conky -c ~/.config/conky/pscircle.conf && \
  conky -c ~/.config/conky/clock.conf &)
pgrep -x picom > /dev/null || picom &
feh --bg-fill ~/.wallpapers/active.jpg

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a dropdown sticky=on state=floating hidden=on rectangle=1916x600+0+0
kitty --class dropdown &

xsetroot -cursor_name left_ptr &
