#! /usr/bin/env zsh


# bspc monitor -d 1 2 3 4 5 6 7 8 9 10
for monitor in $(bspc query --names -M); do `bspc monitor $monitor -d ${monitor}_1 ${monitor}_2 ${monitor}_3 ${monitor}_4 ${monitor}_5`; done

bspc config border_width         2
bspc config window_gap          6
bspc config top_padding         34

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc rule -a plasmashell state=floating border=off
bspc rule -a krunner state=floating border=off

bspc rule -a dropdown sticky=on state=floating hidden=on rectangle=1916x600+0+34
bspc rule -a floatterm state=floating center=on rectangle=600x300+0+0

xsetroot -cursor_name left_ptr &

sleep 3 && (
  kitty --class dropdown &
  pgrep -x sxhkd > /dev/null || sxhkd &
  pgrep -x polybar > /dev/null || polybar top -r &
  pgrep -x alttab > /dev/null || alttab -w 1 -d 1 -bg %{{background}} -fg %{{foreground}} -frame %{{color1}} -font xft:monospace-10 -t 128x150 -i 127x64 &
  # pgrep -x conky > /dev/null || (conky && \
  #   # conky -c ~/.config/conky/gcal.conf && \
  #   conky -c ~/.config/conky/bspwm.conf && \
  #   conky -c ~/.config/conky/pscircle.conf && \
  #   conky -c ~/.config/conky/clock.conf &)
  # pgrep -x picom > /dev/null || picom &
  feh --bg-fill ~/dotfiles/deps/wallpapers/active.jpg
)
