#!/usr/bin/env bash

export SXHKD_SHELL="/bin/sh"

run_once() {
  for p in "$@"; do
    pgrep -x -f "$p" >/dev/null || eval $p &
  done
}

run() {
  for p in "$@"; do
    pkill -f "$p"
    while [ -v "$(pgrep $p)" ]; do sleep 0.05; done
    eval $p &
  done

}

command -v autorandr >/dev/null 2>&1 && autorandr --change
bspc monitor -d '' '󰈹' '󱂬' '' 5 6 7 8 9 10
bspc monitor -r
bspc wm -o

setxkbmap fr -option caps:escape

xinput set-prop "$(xinput list --name-only | grep Touchpad)" "libinput Natural Scrolling Enabled" 1
xinput set-prop "$(xinput list --name-only | grep Touchpad)" "libinput Tapping Enabled" 1

xsetroot -cursor_name left_ptr

source "${XDG_CONFIG_HOME:-${HOME}/.config}/bspwm/variables.sh"

dims=$(xrandr | sed -n 's/^.*current \([0-9]\+\) x \([0-9]\+\).*$/\1x\2/p')
screen_w=$(echo $dims | cut -d'x' -f1)
screen_h=$(echo $dims | cut -d'x' -f2)
scratchterm_w=600
scratchterm_h=800
scratchterm_x=$(($screen_w/2 - scratchterm_w/2))
scratchterm_y=$(($screen_h/2 - scratchterm_h/2))

scratchpad_w=$(($screen_w*85/100))
scratchpad_h=$(($screen_h*85/100))
scratchpad_x=$(($screen_w/2 - scratchpad_w/2))
scratchpad_y=$(($screen_h/2 - scratchpad_h/2))

float_w=$(($screen_w*55/100))
float_h=$(($screen_h*55/100))
float_x=$(($screen_w/2 - float_w/2))
float_y=$(($screen_h/2 - float_h/2))

echo $screen_h $screen_w
echo $scratchpad_h $scratchpad_w $scratchpad_x $scratchpad_y

bspc config border_width 2
bspc config window_gap 12

bspc config focus_follows_pointer true

bspc config split_ratio 0.65
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a '*:*:Picture-in-Picture' state=floating
bspc rule -a pavucontrol state=floating
bspc rule -a Blueman-manager state=floating
bspc rule -a 'popup_term' state=floating "rectangle=${float_w}x${float_h}+${float_x}+${float_y}"
bspc rule -a 'scratchpad' hidden=true state=floating sticky=true "rectangle=${scratchpad_w}x${scratchpad_h}+${scratchpad_x}+${scratchpad_y}"
bspc rule -a 'obsidian' hidden=true state=floating sticky=true "rectangle=${scratchpad_w}x${scratchpad_h}+${scratchpad_x}+${scratchpad_y}"
bspc rule -a 'Capacities' hidden=true state=floating sticky=true "rectangle=${scratchpad_w}x${scratchpad_h}+${scratchpad_x}+${scratchpad_y}"
bspc rule -a 'teams-for-linux' hidden=true state=floating sticky=true "rectangle=${scratchpad_w}x${scratchpad_h}+${scratchpad_x}+${scratchpad_y}"

xdo lower -N Eww

run_once sxhkd pacwall dunst
# ps aux | grep obsidian | grep '/usr/lib/electron' || obsidian
run_once capacities
run_once "nm-applet --indicator"
# run_once "kitty --class scratchpad"
run "eww -c $HOME/.config/eww/bar open bar"
run "caffeine-indicator"
run_once "blueman-applet"
run picom

xset s 900 3600
xss-lock -- $HOME/bin/lock

pkill -USR1 -x sxhkd


notify-send 'BSPWM' 'Config loaded'
