fontconfig:
	@[ -d $(HOME)/.config/fontconfig/conf.d ] || mkdir -p $(HOME)/.config/fontconfig/conf.d
	@ln $(LN_FLAGS) $(DOTFILES)/fontconfig/monospace $(HOME)/.config/fontconfig/conf.d/99-monospace.conf
