plugins:
- wfxr/minimap.vim
- github/copilot.vim
options:
  guifont: mono:h10
globals:
  minimap_width: 10
mappings:
  n:
  - ["<Tab>", "<CMD>bn<CR>"]
  - ["<S-Tab>", "<CMD>bp<CR>"]
  - ["<leader>om", "<CMD>MinimapToggle<CR>"]
colorscheme: catppuccin
