colorscheme: catppuccin
globals:
  mapleader: ' '
mappings:
  n:
  - ["<Tab>", "<CMD>bn<CR>"]
  - ["<S-Tab>", "<CMD>bp<CR>"]
  - ["<leader>om", "<CMD>MinimapToggle<CR>"]
  - ["m", "l"]
  - ["l", "k"]
  - ["k", "j"]
  - ["j", "h"]
  - ["<M-m>", "<C-w><C-l>"]
  - ["<M-l>", "<C-w><C-k>"]
  - ["<M-k>", "<C-w><C-j>"]
  - ["<M-j>", "<C-w><C-h>"]
  - ["<Esc>", "<CMD>noh<CR>"]
  - ["<leader><Space>", "<CMD>b#<CR>"]
  - ["<leader>Q", "<CMD>q<CR>"]
  - ["<leader>q", "<CMD>bd<CR>"]
  - ["<leader>R", "<CMD>so $MYVIMRC<CR>"]
  - ["<leader>P", "<CMD>so $MYVIMRC <BAR> PackerSync<CR>"]
  v:
  - ["m", "l"]
  - ["l", "k"]
  - ["k", "j"]
  - ["j", "h"]
  - ["<", "<gv"]
  - [">", ">gv"]
options:
  autoindent: true
  backspace: indent,eol,start
  clipboard: unnamedplus
  completeopt: menuone,noselect
  expandtab: true
  foldexpr: nvim_treesitter#foldexpr()
  foldmethod: expr
  guifont: mono:h10
  hidden: true
  ignorecase: true
  incsearch: true
  mouse: a
  number: true
  relativenumber: true
  ruler: true
  scrolloff: 4
  shiftwidth: 2
  showmode: true
  smarttab: true
  softtabstop: 2
  splitbelow: true
  splitright: true
  termguicolors: true
  timeoutlen: 300
  undodir:
    lua: vim.fn.stdpath("data") .. "/undodir"
  undofile: true
  wildmenu: true
plugins:
  telescope:
    _: nvim-telescope/telescope.nvim
    requires:
    - nvim-lua/plenary.nvim
    - pwntester/octo.nvim
    - nvim-telescope/telescope-media-files.nvim
    - cljoly/telescope-repo.nvim
    - nvim-telescope/telescope-z.nvim
    - gbrlsnchs/telescope-lsp-handlers.nvim
    - rcarriga/nvim-notify
    - LinArcX/telescope-ports.nvim
    - nvim-telescope/telescope-packer.nvim
    - AckslD/nvim-neoclip.lua
    - nvim-telescope/telescope-arecibo.nvim
    mappings:
      n:
      - ["<leader>f", "<CMD>Telescope find_files<CR>"]
      - ["<leader>a", "<CMD>Telescope live_grep<CR>"]
      - ["<leader>sr", "<CMD>Telescope lsp_references<CR>"]
      - ["<leader>sR", "<CMD>Telescope workspace_references<CR>"]
      - ["<leader>ss", "<CMD>Telescope lsp_dynamic_workspace_symbols<CR>"]
      - ["<leader>b", "<CMD>Telescope buffers<CR>"]
      - ["<leader>sd", "<CMD>Telescope lsp_definitions<CR>"]
      - ["<leader>st", "<CMD>Telescope treesitter<CR>"]
      - ["<F1>", "<CMD>Telescope help_tags<CR>"]
      - ["<leader>gr", "<CMD>Telescope repo list<CR>"]
      - ["<leader>z", "<CMD>Telescope z list<CR>"]
      - ["<leader>sy", "<CMD>Telescope neoclip "]
      - ["<leader>sp", "<CMD>Telescope ports<CR>"]
      - ["<leader>p", "<CMD>Telescope packer<CR>"]
      - ["<leader>sw", "<CMD>lua require'telescope'.extensions.arecibo.websearch()<CR>"]
    luasetup:
      octo: {}
      neoclip: {}
    rocks:
    - openssl
    - lua-http-parser
    custom: |
      require'telescope'.load_extension("repo")
      require'telescope'.load_extension("z")
      require'telescope'.load_extension("ports")
      require'telescope'.load_extension("lsp_handlers")
      require'telescope'.load_extension("packer")
      require'telescope'.load_extension("arecibo")
  toggleterm:
    _: akinsho/toggleterm.nvim
    mappings:
      n:
      - ["<leader>th", "<CMD>ToggleTerm direction=horizontal<CR>"]
      - ["<leader>tt", "<CMD>ToggleTerm direction=float<CR>"]
      - ["<leader>t", "<CMD>ToggleTerm direction=float<CR>"]
      - ["<leader>tv", "<CMD>ToggleTerm direction=vertical<CR>"]
      - ["<leader>gg", "<CMD>TermExec cmd='lazygit && exit' go_back=0 direction=float<CR>"]
      t:
      - ["<Esc>", "<C-\\><C-n>:q<CR>"]
  alpha:
    _: goolord/alpha-nvim
    config: |
      local alpha = require'alpha'
      local dashboard = require'alpha.themes.dashboard'

      vim.g.alpha_configured = true

      -- Set header
      dashboard.section.header.val = {
          "                                                     ",
          "  ███╗   ██╗███████╗ ██████╗ ██╗   ██╗██╗███╗   ███╗ ",
          "  ████╗  ██║██╔════╝██╔═══██╗██║   ██║██║████╗ ████║ ",
          "  ██╔██╗ ██║█████╗  ██║   ██║██║   ██║██║██╔████╔██║ ",
          "  ██║╚██╗██║██╔══╝  ██║   ██║╚██╗ ██╔╝██║██║╚██╔╝██║ ",
          "  ██║ ╚████║███████╗╚██████╔╝ ╚████╔╝ ██║██║ ╚═╝ ██║ ",
          "  ╚═╝  ╚═══╝╚══════╝ ╚═════╝   ╚═══╝  ╚═╝╚═╝     ╚═╝ ",
          "                                                     ",
      }

      -- Set menu
      dashboard.section.buttons.val = {
          dashboard.button("e", "  > New file" , "<CMD>ene <BAR> startinsert <CR>"),
          dashboard.button("f", "  > Find file", "<CMD>Telescope find_files<CR>"),
          dashboard.button("s", "  > Load Session", "<CMD>Telescope z<CR>"),
          dashboard.button("r", "  > Recent"   , "<CMD>Telescope oldfiles<CR>"),
          dashboard.button("q", "  > Quit NVIM", "<CMD>qa<CR>"),
      }

      -- Send config to alpha
      alpha.setup(dashboard.opts)

      -- Disable folding on alpha buffer
      vim.cmd([[
          autocmd FileType alpha setlocal nofoldenable
      ]])
  catpuccin: catppuccin/nvim
  comment:
    _: numToStr/Comment.nvim
    luasetup:
      Comment: {}
  commentBox:
    _: LudoPinelli/comment-box.nvim
    mappings:
      n:
      - ["gC", "<CMD>CBaccbox<CR>"]
  context-vt:
    _: haringsrob/nvim_context_vt
    enabled: false
  copilot: github/copilot.vim
  coq:
    _: ms-jpq/coq_nvim
    globals:
      coq_settings:
        auto_start: true
        keymap:
          pre_select: true
          recommended: false
    mappings:
      i:
      - - "<Esc>"
        - "pumvisible() ? '<C-e><Esc>' : '<Esc>'"
        - expr: true
          silent: true
      - - "<C-c>"
        - "pumvisible() ? '<C-e><C-c>' : '<C-c>'"
        - expr: true
          silent: true
      - - "<BS>"
        - "pumvisible() ? '<C-e><BS>'  : '<BS>'"
        - expr: true
          silent: true
      - - "<CR>"
        - "pumvisible() ? (complete_info().selected == -1 ? '<C-e><CR>' : '<C-y>') : '<CR>'"
        - expr: true
          silent: true
      - - "<Tab>"
        - "pumvisible() ? '<C-n>' : '<Tab>'"
        - expr: true
          silent: true
      - - "<S-Tab>"
        - "pumvisible() ? '<C-p>' : '<BS>'"
        - expr: true
          silent: true
    requires:
    - _: ms-jpq/coq.artifacts
      branch: artifacts
    - ms-jpq/coq.thirdparty
  feline:
    _: feline-nvim/feline.nvim
    luasetup:
      feline: {}
    requires:
    - kyazdani42/nvim-web-devicons
    - lewis6991/gitsigns.nvim
  impatient: lewis6991/impatient.nvim
  indent:
    _: lukas-reineke/indent-blankline.nvim
    luasetup:
      indent_blankline:
        filetype_exclude:
        - alpha
        - oneterm
        show_current_context: true
        show_current_context_start: true
        use_treesitter: true
  kube.nvim: ~/src/personal/kube.nvim
  lightspeed: ggandor/lightspeed.nvim
  lsp:
    _: neovim/nvim-lspconfig
    autocmds:
    - Filetype code-action-menu-* nnoremap <buffer> k j
    - Filetype code-action-menu-* nnoremap <buffer> l k
    - CursorHold * lua require'nvim-lightbulb'.update_lightbulb
    - CursorHoldI * lua require'nvim-lightbulb'.update_lightbulb
    globals:
      lsp_servers:
      - bashls
      - clangd
      - jedi_language_server
      - sumneko_lua
      - rust_analyzer
    custom: |
      for _, s in ipairs(vim.g.lsp_servers) do
        require'lspconfig'[s].setup {}
      end
    mappings:
      n:
      - ["<leader>ld", "<CMD>lua vim.lsp.buf.definition()<CR>"]
      - ["<leader>lD", "<CMD>lua vim.lsp.buf.declaration()<CR>"]
      - ["<leader>lK", "<CMD>lua vim.lsp.buf.hover()<CR>"]
      - ["<leader>li", "<CMD>lua vim.lsp.buf.implementation()<CR>"]
      - ["<leader>ls", "<CMD>lua vim.lsp.buf.signature_help()<CR>"]
      - ["<leader>lt", "<CMD>lua vim.lsp.buf.type_definition()<CR>"]
      - ["<leader>lR", "<CMD>lua vim.lsp.buf.rename()<CR>"]
      - ["<leader>la", "<CMD>lua vim.lsp.buf.range_code_action()<CR>"]
      - ["<leader>lr", "<CMD>lua vim.lsp.buf.references()<CR>"]
      - ["<leader>lf", "<CMD>lua vim.lsp.buf.formatting()<CR>"]
    requires:
    - jubnzv/virtual-types.nvim
    - weilbith/nvim-code-action-menu
    - kosayoda/nvim-lightbulb
    - https://git.sr.ht/~whynothugo/lsp_lines.nvim
  neomake: neomake/neomake
  nord: shaunsingh/nord.nvim
  oneterm:
    _: LoricAndre/OneTerm.nvim
    enabled: false
    globals:
      oneterm_options:
        border: rounded
      oneterm_sessions_path:
        lua: vim.fn.expand(vim.fn.stdpath("data") .. "/sessions/")
      oneterm_yank: true
    mappings:
      n:
      - ["<leader>sf", "<CMD>:OneTerm files_or_git_files<CR>"]
      - ["<leader>sF", "<CMD>:OneTerm files<CR>"]
      - ["<leader>sl", "<CMD>:OneTerm lines<CR>"]
      - ["<leader>sa", "<CMD>:OneTerm ag<CR>"]
      - ["<leader>sg", "<CMD>:OneTerm git<CR>"]
      - ["<leader>sr", "<CMD>:OneTerm references<CR>"]
      - ["<leader>sR", "<CMD>:OneTerm workspace_references<CR>"]
      - ["<leader>ss", "<CMD>:OneTerm symbols<CR>"]
      - ["<leader>sS", "<CMD>:OneTerm ws_symbols<CR>"]
      - ["<leader>sb", "<CMD>:OneTerm buffers<CR>"]
      - ["<leader>sy", "<CMD>:OneTerm yanks<CR>"]
      - ["<leader>t", "<CMD>:OneTerm term<CR>"]
      - ["<leader>r", "<CMD>:OneTerm ranger<CR>"]
      - ["<leader>f", "<CMD>:OneTerm files_or_git_files<CR>"]
      - ["<leader>b", "<CMD>:OneTerm buffers<CR>"]
      - ["<leader>g", "<CMD>:OneTerm git<CR>"]
      - ["<leader>z", "<CMD>:OneTerm z<CR>"]
  persistence:
    _: folke/persistence.nvim
    luasetup:
      persistence:
        dir:
          lua: vim.fn.expand(vim.fn.stdpath('data') .. '/sessions/')
  sidebar:
    _: sidebar-nvim/sidebar.nvim
    autocmds:
    - Filetype SidebarNvim nnoremap <buffer> j h
    - Filetype SidebarNvim nnoremap <buffer> k j
    - Filetype SidebarNvim nnoremap <buffer> l k
    - Filetype SidebarNvim nnoremap <buffer> m l
    luasetup:
      sidebar-nvim:
        buffers:
          icon: 
          ignored_buffers:
          - .*oneterm.*
          show_numbers: true
          sorting: id
        hide_statusline: true
        open: true
        position: right
        sections:
        - buffers
        - files
        - symbols
        - todos
        - diagnostics
    mappings:
      n:
      - ["<leader>os", "<CMD>SidebarNvimToggle<CR>"]
  sniprun:
    _: michaelb/sniprun
    mappings:
      n:
      - ["<Esc>", "<CMD>noh | SnipClose<CR>"]
      - ["<leader>r", "<CMD>SnipRun<CR>"]
      v:
      - ["<leader>r", "<CMD>SnipRun<CR>"]
    run: bash ./install.sh
  tokyodark: tiagovla/tokyodark.nvim
  tokyonight: folke/tokyonight.nvim
  treesitter:
    _: nvim-treesitter/nvim-treesitter
    luasetup:
      nvim-treesitter.configs:
        ensure_installed: all
    run: :TSUpdate
  ynvim: ~/src/personal/ynvim
  rooter: ygm2/rooter.nvim
