#!/usr/bin/env bash

run_once() {
  for p in "$@"; do
    pgrep -x -f "$p" >/dev/null || $p &
  done
}

run() {
  for p in "$@"; do
    pkill -f "$p"
    while [ -v "$(pgrep $p)" ]; do sleep 0.05; done
    $p &
  done

}

autorandr --change
bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc monitor -r
bspc wm -o

setxkbmap fr -option caps:escape

xinput set-prop "$(xinput list --name-only | grep Touchpad)" "libinput Natural Scrolling Enabled" 1
xinput set-prop "$(xinput list --name-only | grep Touchpad)" "libinput Tapping Enabled" 1

xsetroot -cursor_name left_ptr

source "${XDG_CONFIG_HOME:-${HOME}/.config}/bspwm/variables.sh"

run_once sxhkd pacwall dunst
run_once "nm-applet --indicator"
run "eww open bar"
run picom

xset s 900 3600
xss-lock -- $HOME/bin/lock


dims=$(xrandr | sed -n 's/^.*current \([0-9]\+\) x \([0-9]\+\).*$/\1x\2/p')
float_w=600
float_h=800
float_x=$(($(echo $dims | cut -d'x' -f1)/2 - float_w/2))
float_y=$(($(echo $dims | cut -d'x' -f2)/2 - float_h/2))

echo $float_x $float_y $float_w $float_h

bspc config border_width 2
bspc config window_gap 12

bspc config focus_follows_pointer true

bspc config split_ratio 0.65
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a '*:*:Picture-in-Picture' state=floating
bspc rule -a pavucontrol state=floating
bspc rule -a pavucontrol state=floating
bspc rule -a 'popup_term' state=floating "rectangle=${float_w}x${float_h}+${float_x}+${float_y}"

notify-send 'BSPWM' 'Config loaded'
