[theme]
file = "lule.toml"
[icons]
name = "awesome"
[icons.overrides]
backlight_empty = " "
backlight_full = " "
backlight_partial1 = " "
backlight_partial2 = " "
backlight_partial3 = " "
update =  ""

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]
hide_when_empty = true

[[block]]
block = "sound"
on_click = "pavucontrol"

[[block]]
block = "backlight"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "custom"
command = "/home/loric/dotfiles/status cpu"
interval = 1
json = true

[[block]]
block = "networkmanager"
on_click = "networkmanager_dmenu"

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 1
format = "%a %d/%m %R:%S"
