idle_bg = "%{{background}}"
idle_fg = "%{{foreground}}"
info_bg = "%{{color2}}"
info_fg = "%{{background}}"
good_bg = "%{{color9}}"
good_fg = "%{{background}}"
warning_bg = "%{{color4}}"
warning_fg = "%{{background}}"
critical_bg = "%{{color8}}"
critical_fg = "%{{background}}"
separator = " "
separator_fg = "auto"
separator_bg = "auto"
alternating_tint_bg = "%{{background}}"
alternating_tint_fg = "%{{background}}"
