##Juddly's Custom Conky##
conky.config = {
    alignment = 'middle_right',
    use_xft = true,
    xftalpha = 1,
    font = 'monospace:normal:size=48',
    text_buffer_size = 2048,
    update_interval = 1,
    total_run_times = 0,
    background = true,
    double_buffer = true,
    imlib_cache_size = 0,
    cpu_avg_samples = 2,
    own_window = true,
    own_window_class = 'Conky',
    own_window_argb_visual = true,
    own_window_argb_value = 255,
    own_window_transparent = true,
    own_window_type = 'override',
    own_window_hints = 'undecorated,below',
    own_window_colour = '000000',
    draw_shades = false,
    default_shade_color = '000000',
    draw_outline = no,
    default_outline_color = '000000',
    draw_borders = false,
    gap_x = 10,
    gap_y = -50,
    minimum_height = 100,
    minimum_width = 400,
    draw_graph_borders = true,
    show_graph_scale = no,
    show_graph_range = no,
    short_units = no,
    override_utf8_locale = yes,
    uppercase = yes,
    default_color = 'ffffff',
    color1 = '%{{color1}}',
    color2 = '%{{color2}}',
    color3 = '%{{color3}}',
    color4 = '%{{color4}}',
    color5 = '%{{color5}}',
    color6 = '%{{color6}}',
    color7 = '%{{color7}}',
    use_spacer = none,
}

conky.text = [[
${alignr 10}${color2}${font monospace:bold:size=48}${time %H:%M:%S}
${alignr 10}${font monospace:bold:size=16}${color4}${time %a %d %b}${color}
]]


