require'utils'

map('n', '<M-j>', '<C-W><C-H>', {noremap = true, silent = true})
map('n', '<M-k>', '<C-W><C-J>', {noremap = true, silent = true})
map('n', '<M-l>', '<C-W><C-K>', {noremap = true, silent = true})
map('n', '<M-m>', '<C-W><C-L>', {noremap = true, silent = true})
map('n', '<up>', '<Nop>', {noremap = true, silent = true})
map('n', '<down>', '<Nop>', {noremap = true, silent = true})
map('n', '<left>', '<Nop>', {noremap = true, silent = true})
map('n', '<right>', '<Nop>', {noremap = true, silent = true})
map('n', '<Tab>', ':bn<CR>', {noremap = true, silent = true})
map('n', '<S-Tab>', ':bp<CR>', {noremap = true, silent = true})
map('n', '<C-Left>', '<C-W><C-H>', {noremap = true, silent = true})
map('n', '<C-Down>', '<C-W><C-J>', {noremap = true, silent = true})
map('n', '<C-Up>', '<C-W><C-K>', {noremap = true, silent = true})
map('n', '<C-Right>', '<C-W><C-L>', {noremap = true, silent = true})
map('n', '<leader><Space>', ':b#<CR>', {noremap = true, silent = true})
map('n', '<leader>q', ':bw<CR>', {noremap = true, silent = true})
-- move with jklm
map('n', 'j', 'h', {noremap = true, silent = true})
map('n', 'k', 'j', {noremap = true, silent = true})
map('n', 'l', 'k', {noremap = true, silent = true})
map('n', 'm', 'l', {noremap = true, silent = true})
map('v', 'j', 'h', {noremap = true, silent = true})
map('v', 'k', 'j', {noremap = true, silent = true})
map('v', 'l', 'k', {noremap = true, silent = true})
map('v', 'm', 'l', {noremap = true, silent = true})
-- Misc
map('n', 'ù', 'm', {noremap = true, silent = true})
map('n', 'è', '`', {noremap = true, silent = true})
map('i', '<C-BS>', '<C-W>', {noremap = true, silent = true})
map('n', 'zz', 'za', {noremap = true, silent = true})
map('v', '<', '<gv', {noremap = true, silent = true})
map('v', '>', '>gv', {noremap = true, silent = true})
map('n', 'x', '"_x', {noremap = true, silent = true})
map('n', 'gR', ':s/<C-R><C-W>/', {noremap = true, silent = true})
map('n', 'gh', ':noh<CR>', {noremap = true, silent = true})
-- map('v', "'", ":s/\\%V\\(.*\\)\\%V/\\'\\1\\'/<CR>:noh<CR>", {noremap = true, silent = true})
-- map('v', '"', ':s/\\%V\\(.*\\)\\%V/\\"\\1\\"/<CR>:noh<CR>', {noremap = true, silent = true})


map('i', '<PageUp>', '<Nop>', {noremap = true, silent = true})
map('i', '<PageDown>', '<Nop>', {noremap = true, silent = true})

map('n', '<PageUp>', '<Nop>', {noremap = true, silent = true})
map('n', '<PageDown>', '<Nop>', {noremap = true, silent = true})

map('i', '<expr> <Tab>', 'pumvisible() ? "<C-n>" : "<Tab>"', {noremap = true, silent = true})
map('i', '<expr> <S-Tab>', ' pumvisible() ? "<C-p>" : "<S-Tab>"', {noremap = true, silent = true})

map('n', '1', ':b 1<CR>', {noremap = true})
map('n', '2', ':b 2<CR>', {noremap = true})
map('n', '3', ':b 3<CR>', {noremap = true})
map('n', '4', ':b 4<CR>', {noremap = true})
map('n', '5', ':b 5<CR>', {noremap = true})
map('n', '6', ':b 6<CR>', {noremap = true})
map('n', '7', ':b 7<CR>', {noremap = true})
map('n', '8', ':b 8<CR>', {noremap = true})
map('n', '9', ':b 9<CR>', {noremap = true})
map('n', '0', ':b 10<CR>', {noremap = true})
