#!/usr/bin/env bash

# This is the example configuration file for river.
#
# If you wish to edit this, you will probably want to copy it to
# $XDG_CONFIG_HOME/river/init or $HOME/.config/river/init first.
#
# See the river(1), riverctl(1), and rivercarro(1) man pages for complete
# documentation.

# Note: the "Super" modifier is also known as Logo, GUI, Windows, Mod4, etc.

# Super+Shift+Return to start an instance of foot (https://codeberg.org/dnkl/foot)
term="{{app.term}}"
browser="{{app.browser}}"
drun="wofi --show drun"
run="wofi --show run"
lock="waylock --init-color '#{{color.bg}}' --fail-color '#{{color.2}}' --input-color '#{{color.9}}'"


riverctl map normal Super Return spawn "$term"
riverctl map normal Super B spawn "$browser"
riverctl map normal Super D spawn "$drun"
riverctl map normal Super R spawn "$run"
riverctl map normal Control+Mod1 L spawn "$lock"

# Super+Q to close the focused view
riverctl map normal Super Q close

# Super+Shift+E to exit river
riverctl map normal Super+Shift E exit
riverctl map normal Super+Shift R spawn "zsh -ic 'yrice && ~/.config/river/init'"

# Super+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal Super M focus-view next
riverctl map normal Super J focus-view previous

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal Super+Shift M swap next
riverctl map normal Super+Shift J swap previous

# Super+Period and Super+Comma to focus the next/previous output
riverctl map normal Super L focus-output next
riverctl map normal Super K focus-output previous

# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Super+Shift L send-to-output next
riverctl map normal Super+Shift K send-to-output previous

# Super+Return to bump the focused view to the top of the layout stack
riverctl map normal Super Space zoom

# Super+H and Super+L to decrease/increase the main ratio of rivercarro(1)
riverctl map normal Super P send-layout-cmd rivercarro "main-ratio -0.05"
riverctl map normal Super U send-layout-cmd rivercarro "main-ratio +0.05"

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of rivercarro(1)
riverctl map normal Super O send-layout-cmd rivercarro "main-count +1"
riverctl map normal Super I send-layout-cmd rivercarro "main-count -1"

# Super+Alt+{H,J,K,L} to move views
riverctl map normal Super+Alt J move left 100
riverctl map normal Super+Alt K move down 100
riverctl map normal Super+Alt L move up 100
riverctl map normal Super+Alt M move right 100

# Super+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal Super+Alt+Control J snap left
riverctl map normal Super+Alt+Control K snap down
riverctl map normal Super+Alt+Control L snap up
riverctl map normal Super+Alt+Control M snap right

# Super+Alt+Shif+{H,J,K,L} to resize views
riverctl map normal Super+Alt+Shift J resize horizontal -100
riverctl map normal Super+Alt+Shift K resize vertical 100
riverctl map normal Super+Alt+Shift L resize vertical -100
riverctl map normal Super+Alt+Shift M resize horizontal 100

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

keys=("ampersand" "eacute" "quotedbl" "apostrophe" "parenleft" "minus" "egrave" "underscore" "ccedilla" "agrave")
for i in $(seq 0 9)
do
    tag=$((1 << $i))
    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super ${keys[$i]} set-focused-tags $tag

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift ${keys[$i]} set-view-tags $tag

    # Super+Ctrl+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control ${keys[$i]} toggle-focused-tags $tag

    # Super+Shift+Ctrl+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control ${keys[$i]} toggle-view-tags $tag
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super twosuperior set-focused-tags $all_tags
riverctl map normal Super+Shift twosuperior set-view-tags $all_tags

# Super+Space to toggle float
riverctl map normal Super F toggle-float

# Super+F to toggle fullscreen
riverctl map normal Super Z send-layout-cmd rivercarro "main-location monocle"

# Super+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Super Up    send-layout-cmd rivercarro "main-location top"
riverctl map normal Super Right send-layout-cmd rivercarro "main-location right"
riverctl map normal Super Down  send-layout-cmd rivercarro "main-location bottom"
riverctl map normal Super Left  send-layout-cmd rivercarro "main-location left"

riverctl map normal Super+Shift Tab spawn "cycle-focused-tags previous 10"
riverctl map normal Super Tab spawn "cycle-focused-tags next 10"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
riverctl map passthrough Super F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'pamixer -i 5'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'pamixer -d 5'
    riverctl map $mode None XF86AudioMute         spawn 'pamixer --toggle-mute'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # Control screen backlight brighness with light (https://github.com/haikarainen/light)
    riverctl map $mode None XF86MonBrightnessUp   spawn 'light -A 5'
    riverctl map $mode None XF86MonBrightnessDown spawn 'light -U 5'
    riverctl map $mode None Print 'grim - | tee "/home/loric/Pictures/$(date +%Y-%m-%d-%H-%M-%S).png" | wl-copy'
    riverctl map $mode Super Print 'grim -g - | tee "/home/loric/Pictures/$(date +%Y-%m-%d-%H-%M-%S).png" | wl-copy'
done

# Set background and border color
riverctl background-color 0x{{color.bg}}
riverctl border-color-focused 0x{{color.5}}
riverctl border-color-unfocused 0x{{color.9}}

# Config
riverctl focus-follows-cursor normal
riverctl set-cursor-warp normal
input="$(riverctl list-inputs | grep Touchpad)"
riverctl input $input accel-profile adaptive
riverctl input $input click-method clickfinger
riverctl input $input disable-while-typing disabled
riverctl input $input natural-scroll enabled
riverctl input $input tap enabled

# Set keyboard repeat rate
riverctl set-repeat 50 300

/usr/lib/disman_backend_launcher &
# displays=$(wayland-info | sed -n "s/^.*'\(e\?DP-\?[0-9]\)'.*$/\1/p" | sort --uniq)
# while [ -z $displays ]; do
#   displays=$(dismanctl -o -j | jq -r '.outputs[].name' 2>/dev/null)
#   sleep 0.1
# done
# pkill yambar
# for display in $displays; do
#   (echo "monitor: &monitor $display" && cat ~/.config/yambar/config.yaml) > /tmp/yambar.$display.yaml
#   yambar -c /tmp/yambar.$display.yaml &
# done
dismanctl output.DP-1.position.0,0
dismanctl output.eDP-1.position.1920,0 2>&1 # Setup monitor layout
pkill mako; mako &
pkill swayidle; swayidle -w timeout 600 "$lock" &
pkill udiskie; udiskie &
pkill battery_warning.sh; battery_warning.sh &

scratch_tag=$(( 1 << 20 ))
kitty --class scratchterm &
sleep 1
riverctl resize horizontal +2000
riverctl resize vertical +2000
riverctl resize vertical -400
riverctl snap up
riverctl set-view-tags ${scratch_tag}
riverctl map normal Super T toggle-focused-tags ${scratch_tag}
riverctl map normal Super+Shift T set-view-tags ${scratch_tag}
all_but_scratch_tag=$(( ((1 << 32) - 1) ^ $scratch_tag ))
riverctl spawn-tagmask ${all_but_scratch_tag}

# Set and exec into the default layout generator, rivercarro.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivercarro
exec rivercarro
