#!/bin/sh

if [ "$1" = "focus" ]; then
	name=$(bspc query -D -d $2 --names)
	notify-send "[bspwm] Focus desktop $name"
	bspc desktop -f $2
	exit
fi

workspaces() {
	ids=$(bspc query -D)
	occupied=$(bspc query -D -d .occupied --names)
	focused=$(bspc query -D -d focused --names)

	# Unoccupied
	un="0"

	# check if Occupied
	o1=$(bspc query -D -d .occupied --names | grep "$ws1" )
	o2=$(bspc query -D -d .occupied --names | grep "$ws2" )
	o3=$(bspc query -D -d .occupied --names | grep "$ws3" )
	o4=$(bspc query -D -d .occupied --names | grep "$ws4" )
	o5=$(bspc query -D -d .occupied --names | grep "$ws5" )
	o6=$(bspc query -D -d .occupied --names | grep "$ws6" )

	# check if Focused
	f1=$(bspc query -D -d focused --names | grep "$ws1" )
	f2=$(bspc query -D -d focused --names | grep "$ws2" )
	f3=$(bspc query -D -d focused --names | grep "$ws3" )
	f4=$(bspc query -D -d focused --names | grep "$ws4" )
	f5=$(bspc query -D -d focused --names | grep "$ws5" )
	f6=$(bspc query -D -d focused --names | grep "$ws6" )

	# check if Urgent
	# u1=$(bspc query -D -d .urgent --names | grep 1)
	# u2=$(bspc query -D -d .urgent --names | grep 2)
	# u3=$(bspc query -D -d .urgent --names | grep 3)
	# u4=$(bspc query -D -d .urgent --names | grep 4)
	# u5=$(bspc query -D -d .urgent --names | grep 5)
	res='(box	:class "workspaces" :orientation "v"	:halign "center"	:valign "start"	 :space-evenly "false" :spacing "-5"'
	for ws in $ids; do
		name=$(bspc query -D -d $ws --names)
		class="workspace"
		if [ ! -z "$(bspc query -D -d $ws.focused)" ]; then
			class="$class focused"
		fi
		if [ ! -z "$(bspc query -D -d $ws.occupied)" ]; then
			class="$class occupied"
		fi

		res="$res (button :onclick \"$0 focus $ws\"	:class	\"$class\"	\"$name\") "
	done

	echo "$res)"
}

workspaces

bspc subscribe desktop node_transfer | while read -r _ ; do
	workspaces
done
