build_zsh:
	@echo "ZSH built"

link_zsh:
	ln $(LN_FLAGS) $(DOTFILES)/zsh/zshrc $(HOME)/.zshrc
	ln $(LN_FLAGS) $(DOTFILES)/zsh/aliases $(HOME)/.zshaliases
	ln $(LN_FLAGS) $(DOTFILES)/zsh/profile $(HOME)/.zprofile
