zsh:
	@mkdir $(HOME)/.cache/zsh
	@ln $(LN_FLAGS) $(DOTFILES)/zsh/zshrc $(HOME)/.zshrc
	ln $(LN_FLAGS) $(DOTFILES)/zsh/aliases $(HOME)/.zshaliases
	ln $(LN_FLAGS) $(DOTFILES)/zsh/profile $(HOME)/.zprofile
	ln $(LN_FLAGS) $(DOTFILES)/zsh/antigen.zsh $(HOME)/.antigen.zsh
