[keys]
  up = ["up", "l"]
  down = ["down", "k"]
  apply = ["enter"]
  cancel = ["esc"]
  toggle_select = [" "]
  new = ["n"]
  commit = ["c"]
  refresh = ["ctrl+r"]
  abandon = ["a"]
  diff = ["d"]
  quit = ["q"]
  help = ["?"]
  describe = ["D"]
  edit = ["e"]
  diffedit = ["E"]
  absorb = ["A"]
  split = ["s"]
  squash = ["S"]
  undo = ["u"]
  evolog = ["v"]
  revset = ["Z"]
  quick_search = ["/"]
  quick_search_cycle = ["'"]
  custom_commands = ["x"]
  [keys.rebase]
    mode = ["r"]
    revision = ["r"]
    source = ["s"]
    branch = ["B"]
    after = ["a"]
    before = ["b"]
    onto = ["d"]
    insert = ["i"]
  [keys.details]
    mode = ["z"]
    close = ["j"]
    split = ["s"]
    restore = ["r"]
    diff = ["d"]
    select = ["m", " "]
    revisions_changing_file = ["*"]
  [keys.preview]
    mode = ["p"]
    scroll_up = ["ctrl+p"]
    scroll_down = ["ctrl+n"]
    half_page_down = ["ctrl+d"]
    half_page_up = ["ctrl+u"]
    expand = ["ctrl+h"]
    shrink = ["ctrl+l"]
  [keys.bookmark]
    mode = ["b"]
    set = ["B"]
    delete = ["d"]
    move = ["m"]
    forget = ["f"]
    track = ["t"]
    untrack = ["u"]
  [keys.git]
    mode = ["g"]
    push = ["p"]
    fetch = ["f"]
  [keys.oplog]
    mode = ["o"]
    restore = ["r"]

[ui]
  highlight_light = "#a0a0a0"
  highlight_dark = "#${color0}"
  auto_refresh_interval = 0

[preview]
  extra_args = []
  show_at_start = true
  width_percentage = 50.0
  width_increment_percentage = 5.0

[oplog]
  limit = 200

[custom_commands]
