link_fish:
	ln $(LN_FLAGS) $(DOTFILES)/fish/config.fish $(HOME)/.config/fish/
	ln $(LN_FLAGS) $(DOTFILES)/fish/abbr.fish $(HOME)/.config/fish
	ln $(LN_FLAGS) $(DOTFILES)/fish/functions/* $(HOME)/.config/fish/functions/
