set preview_images true
set preview_images_method kitty
set show_hidden_bookmarks true
set draw_progress_bar_in_status_bar true
set mouse_enabled true
set display_size_in_main_column true
set display_free_space_in_status_bar true
copymap l m
copymap k l
copymap j k
copymap h j
map h set_bookmark %any
map uh unset_bookmark %any
