# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[](bold purple)'
error_symbol = '[](bold red)'

[git_metrics]
disabled = false
# added_style = 'bold blue'
# format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[kubernetes]
disabled = false
detect_files = ['Chart.yaml']
